#!/usr/bin/env bash
# Script that displays listening TCP and UDP ports with PID/Program name

echo "Active Internet connections (only servers)"
cat /proc/net/tcp /proc/net/tcp6 | awk '
NR>1 {
    split($2,a,":")
    port = strtonum("0x" a[2])
    print "tcp *:"port
}'

cat /proc/net/udp /proc/net/udp6 | awk '
NR>1 {
    split($2,a,":")
    port = strtonum("0x" a[2])
    print "udp *:"port
}'

echo "Active UNIX domain sockets (only servers)"
cat /proc/net/unix

