#!/usr/bin/env bash
# Script that displays listening TCP and UDP ports with PID/Program name

echo "Active Internet connections (only servers)"
netstat -tulpn

echo "Active UNIX domain sockets (only servers)"
netstat -lp | grep unix

